// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gadhittana01/cases-app-server/db/repository"
	"github.com/gadhittana01/cases-app-server/handler"
	"github.com/gadhittana01/cases-app-server/providers"
	"github.com/gadhittana01/cases-app-server/routes"
	"github.com/gadhittana01/cases-app-server/service"
	"github.com/gadhittana01/cases-modules/utils"
)

// Injectors from wire.go:

func InitializeApp(db utils.PGXPool, config *utils.Config) (*App, error) {
	repositoryRepository := repository.NewRepository(db)
	userService := service.NewUserService(repositoryRepository, config)
	userHandler := handler.NewUserHandler(userService)
	caseService := service.NewCaseService(repositoryRepository)
	client, err := providers.NewS3Client(config)
	if err != nil {
		return nil, err
	}
	presignClient := providers.NewPresignClient(client)
	fileService := service.NewFileService(repositoryRepository, client, presignClient, config)
	caseHandler := handler.NewCaseHandler(caseService, fileService)
	quoteService := service.NewQuoteService(repositoryRepository)
	quoteHandler := handler.NewQuoteHandler(quoteService)
	marketplaceService := service.NewMarketplaceService(repositoryRepository)
	marketplaceHandler := handler.NewMarketplaceHandler(marketplaceService)
	pusherClient := providers.NewPusherClient(config)
	paymentService := service.NewPaymentService(repositoryRepository, config, pusherClient)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	fileHandler := handler.NewFileHandler(fileService)
	webhookHandler := handler.NewWebhookHandler(paymentService, config)
	engine := routes.SetupRoutes(userHandler, caseHandler, quoteHandler, marketplaceHandler, paymentHandler, fileHandler, webhookHandler, config)
	app := NewApp(engine, config)
	return app, nil
}
