// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Case struct {
	ID          uuid.UUID          `json:"id"`
	ClientID    uuid.UUID          `json:"client_id"`
	Title       string             `json:"title"`
	Category    string             `json:"category"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CaseFile struct {
	ID        uuid.UUID          `json:"id"`
	CaseID    uuid.UUID          `json:"case_id"`
	FileName  string             `json:"file_name"`
	FilePath  string             `json:"file_path"`
	FileSize  int64              `json:"file_size"`
	MimeType  string             `json:"mime_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                    uuid.UUID          `json:"id"`
	QuoteID               uuid.UUID          `json:"quote_id"`
	StripePaymentIntentID string             `json:"stripe_payment_intent_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Quote struct {
	ID           uuid.UUID          `json:"id"`
	CaseID       uuid.UUID          `json:"case_id"`
	LawyerID     uuid.UUID          `json:"lawyer_id"`
	Amount       pgtype.Numeric     `json:"amount"`
	ExpectedDays int32              `json:"expected_days"`
	Note         pgtype.Text        `json:"note"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Role         string             `json:"role"`
	Jurisdiction pgtype.Text        `json:"jurisdiction"`
	BarNumber    pgtype.Text        `json:"bar_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
