// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptQuote(ctx context.Context, id uuid.UUID) (*Quote, error)
	CountCaseFilesByCaseID(ctx context.Context, caseID uuid.UUID) (int64, error)
	CountCasesByClientID(ctx context.Context, clientID uuid.UUID) (int64, error)
	CountOpenCases(ctx context.Context, arg *CountOpenCasesParams) (int64, error)
	CountQuotesByCaseID(ctx context.Context, caseID uuid.UUID) (int64, error)
	CountQuotesByLawyerID(ctx context.Context, arg *CountQuotesByLawyerIDParams) (int64, error)
	CreateCase(ctx context.Context, arg *CreateCaseParams) (*Case, error)
	CreateCaseFile(ctx context.Context, arg *CreateCaseFileParams) (*CaseFile, error)
	CreatePayment(ctx context.Context, arg *CreatePaymentParams) (*Payment, error)
	CreateQuote(ctx context.Context, arg *CreateQuoteParams) (*Quote, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteCaseFile(ctx context.Context, id uuid.UUID) error
	GetAcceptedQuoteByCaseID(ctx context.Context, caseID uuid.UUID) (*Quote, error)
	GetCaseByID(ctx context.Context, id uuid.UUID) (*Case, error)
	GetCaseFileByID(ctx context.Context, id uuid.UUID) (*CaseFile, error)
	GetCaseFilesByCaseID(ctx context.Context, caseID uuid.UUID) ([]*CaseFile, error)
	GetCaseWithClient(ctx context.Context, id uuid.UUID) (*GetCaseWithClientRow, error)
	GetCasesByClientID(ctx context.Context, arg *GetCasesByClientIDParams) ([]*Case, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (*Payment, error)
	GetPaymentByQuoteID(ctx context.Context, quoteID uuid.UUID) (*Payment, error)
	GetPaymentByStripePaymentIntentID(ctx context.Context, stripePaymentIntentID string) (*Payment, error)
	GetQuoteByCaseAndLawyer(ctx context.Context, arg *GetQuoteByCaseAndLawyerParams) (*Quote, error)
	GetQuoteByID(ctx context.Context, id uuid.UUID) (*Quote, error)
	GetQuotesByCaseID(ctx context.Context, caseID uuid.UUID) ([]*GetQuotesByCaseIDRow, error)
	GetQuotesByLawyerID(ctx context.Context, arg *GetQuotesByLawyerIDParams) ([]*GetQuotesByLawyerIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	ListOpenCases(ctx context.Context, arg *ListOpenCasesParams) ([]*ListOpenCasesRow, error)
	RejectOtherQuotes(ctx context.Context, arg *RejectOtherQuotesParams) ([]*Quote, error)
	UpdateCaseStatus(ctx context.Context, arg *UpdateCaseStatusParams) (*Case, error)
	UpdatePaymentStatus(ctx context.Context, arg *UpdatePaymentStatusParams) (*Payment, error)
	UpdateQuote(ctx context.Context, arg *UpdateQuoteParams) (*Quote, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
